Traceback (most recent call last):
  File "/Users/promiseosaineekpo/Cornell Repos/robotouille/robotouille/lib/python3.8/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 40, in _patch_env
    import shimmy
ModuleNotFoundError: No module named 'shimmy'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    simulator(args.environment_name, args.seed, args.noisy_randomization)
  File "/Users/promiseosaineekpo/Cornell Repos/hosp_robotouille/robotouille/robotouille_simulator.py", line 51, in simulator
    model = PPO.load(file, env=rl_env)
  File "/Users/promiseosaineekpo/Cornell Repos/robotouille/robotouille/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 712, in load
    env = cls._wrap_env(env, data["verbose"])
  File "/Users/promiseosaineekpo/Cornell Repos/robotouille/robotouille/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 216, in _wrap_env
    env = _patch_env(env)
  File "/Users/promiseosaineekpo/Cornell Repos/robotouille/robotouille/lib/python3.8/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 42, in _patch_env
    raise ImportError(
ImportError: Missing shimmy installation. You provided an OpenAI Gym environment. Stable-Baselines3 (SB3) has transitioned to using Gymnasium internally. In order to use OpenAI Gym environments with SB3, you need to install shimmy (`pip install 'shimmy>=0.2.1'`).